name: star
description: Note App using firebase , Getx and shared preferences.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  # cupertino icons
  cupertino_icons: ^1.0.2

  # External Dependencies Packages 
  jiffy: ^5.0.0
  #image_picker: ^0.8.6
  http: ^0.13.5
  shared_preferences: ^2.0.15
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.9
  cloud_firestore: ^4.3.0
  #firebase_messaging: ^10.0.4
  firebase_auth: ^4.2.3
  #dropdown_search: ^0.6.3
  google_sign_in: ^5.4.2
  font_awesome_flutter: ^10.3.0 
  url_launcher: ^6.1.7
  flutter_rating_bar: ^4.0.1
  get: 
  dartz:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application .
  assets:
    - assets/images/note.json
  #   - images/a_dot_ham.jpeg



  # Fonts Part 
  fonts:
  - family: GowunBatang
    fonts:
    - asset: assets/fonts/GowunBatang-Regular.ttf

  - family: Courgette
    fonts:
    - asset: assets/fonts/cour/Courgette-Regular.ttf

